on:
  push:
    tags:
    - 'v*'

name: Upload Release Asset

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Upload Release Asset
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: build
    - uses: actions/upload-artifact@v2
      name: Upload artifact
      with:
        name: artifact
        path: build/distributons/*.zip

  create-release:
    runs-on: ubuntu-latest
    name: create github release
    needs: build
    steps:
    - uses: actions/download-artifact@v2
      name: Download artifact
      with:
        name: artifact
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release v${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
    - name: Upload Release Asset(Linux,zip)
      id: upload-release-asset-linux
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: omegat-browser-Linux-${{ steps.get_version.outputs.VERSION }}.zip
        asset_name: omegat-browser-Linux-${{ steps.get_version.outputs.VERSION }}.zip
        asset_content_type: application/zip
    - name: Upload Release Asset(Windows,zip)
      id: upload-release-asset-win
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: omegat-browser-Windows-${{ steps.get_version.outputs.VERSION }}.zip
        asset_name: omegat-browser-Windows-${{ steps.get_version.outputs.VERSION }}.zip
        asset_content_type: application/gzip
    - name: Upload Release Asset(mac,zip)
      id: upload-release-asset-mac
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: omegat-browser-macOS-${{ steps.get_version.outputs.VERSION }}.zip
        asset_name: omegat-browser-macOS-${{ steps.get_version.outputs.VERSION }}.zip
        asset_content_type: application/zip

